AlxOnRails/config/routes.rb
AlxOnRails::Application.routes.draw do
  
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end

  resources :quotes
  resources :activities
  resources :users

  root :to => 'quotes#index'

end

AlxOnRails/app/models/quote.rb
class Quote < ActiveRecord::Base
	include PublicActivity::Common
  attr_accessible :author, :rating, :text, :url

	# tracked except: :update, owner: ->(controller, model) { controller.current_user }

	validates :text, presence: true, length: { minimum: 5, maximum: 800 }
	validates :rating, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 10}
end

AlxOnRails/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  validates :name, presence: true, uniqueness: true 
  has_secure_password
end

AlxOnRails/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
  	 @activities = PublicActivity::Activity.order('created_at desc')
  end
end

AlxOnRails/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  	@total_quotes = Quote.count
  end
end

AlxOnRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include PublicActivity::StoreController
	protect_from_forgery
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  hide_action :current_user

end

AlxOnRails/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.find(:all, :order => 'created_at DESC')
    @title = "Favorite Quotes"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @quotes }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    @quote = Quote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/new
  # GET /quotes/new.json
  def new
    @quote = Quote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @quote }
    end
  end

  # GET /quotes/1/edit
  def edit
    @quote = Quote.find(params[:id])
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(params[:quote])

    respond_to do |format|
      if @quote.save
        @quote.create_activity :create, owner: current_user
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render json: @quote, status: :created, location: @quote }
      else
        format.html { render action: "new" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /quotes/1
  # PUT /quotes/1.json
  def update
    @quote = Quote.find(params[:id])

    respond_to do |format|
      if @quote.update_attributes(params[:quote])
        @quote.create_activity :update, owner: current_user
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end
end

AlxOnRails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_name(params[:name])
  	if user and user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to admin_url
  	else
  		redirect_to login_url, alert: "Invalid username and/or password"
  	end
  end

  def destroy
	session[:user_id] = nil
	redirect_to store_url, notice: "Logged out"
  end
end

AlxOnRails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully created." }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

AlxOnRails/app/helpers/activities_helper.rb
module ActivitiesHelper
end

AlxOnRails/app/helpers/admin_helper.rb
module AdminHelper
end

AlxOnRails/app/helpers/application_helper.rb
module ApplicationHelper
end

AlxOnRails/app/helpers/quotes_helper.rb
module QuotesHelper
end

AlxOnRails/app/helpers/sessions_helper.rb
module SessionsHelper
end

AlxOnRails/app/helpers/users_helper.rb
module UsersHelper
end

AlxOnRails/app/views/activities/index.html.erb
<div id='activity_wrapper'>

	<h1>Activities</h1>
		<ul>
			<% @activities.each do |activity| %>
	  			<%= render_activity activity %>
			<% end %>
		</ul>
	<%= link_to 'Back', quotes_path %>

</div>

AlxOnRails/app/views/admin/index.html.erb
<h1>Welcome</h1> 
It's <%= Time.now %>
We have <%= pluralize(@total_quotes, "quote") %>.

AlxOnRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlxOnRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>

AlxOnRails/app/views/public_activity/quote/_create.html.erb
<% if activity.trackable %>
	<li>The quote <em>"<%= activity.trackable.text %>"</em> was added by you <%= time_ago_in_words(activity.created_at) %> ago.</li>
<% else %>
<% end %>

AlxOnRails/app/views/public_activity/quote/_destroy.html.erb
<% if activity.trackable %>
	<li>The quote <em>"<%= activity.trackable.text %>"</em> was deleted by you <%= time_ago_in_words(activity.created_at) %> ago.</li>
<% else %>
  	<li>A quote was deleted by you <%= time_ago_in_words(activity.created_at) %> ago.</li>
<% end %>

AlxOnRails/app/views/public_activity/quote/_update.html.erb
<% if activity.trackable %>
	<li>The quote <em>"<%= activity.trackable.text %>"</em> was updated by you <%= time_ago_in_words(activity.created_at) %> ago.</li>
<% else %>
<% end %>

AlxOnRails/app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AlxOnRails/app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

AlxOnRails/app/views/quotes/index.html.erb
<div id='quote_wrapper'>

  <span class="title"><%= @title %></span>

  <span class="activities"><%= link_to 'Recent activities', activities_path %></span>

  <div class="new_quote">
    <%= link_to '+', new_quote_path %>
  </div>

  <% @quotes.each do |quote| %>

    <span class="text"><%= link_to quote.text, quote.url %></span>

    <ul class='quote_info'>
      <li class="author"><strong>Author: </strong><%= quote.author %></li>
      <li class="rating" id='rating_0<%= quote.rating %>'><strong>Rating: </strong><%= quote.rating %></li>
      <li class="count"><strong>Character Count: </strong><%= quote.text.length %>
    </ul>

    <ul class='list_actions'>
      <li><%= link_to 'Edit', edit_quote_path(quote) %></li>
      <li><%= link_to 'Delete', quote, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>

  <% end %>

</div>

AlxOnRails/app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

AlxOnRails/app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @quote.text %>
</p>

<p>
  <b>Author:</b>
  <%= @quote.author %>
</p>

<p>
  <b>Url:</b>
  <%= @quote.url %>
</p>

<p>
  <b>Rating:</b>
  <%= @quote.rating %>
</p>


<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>

AlxOnRails/app/views/users/_form.html.erb
<div class="user_form">
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset>
      <legend>Enter User Details</legend>

      <div>
        <%= f.label :name %>:
        <%= f.text_field :name, size: 40 %>
      </div>

      <div>
        <%= f.label :password, 'Password' %>:
        <%= f.password_field :password, size: 40 %>
      </div>
      
      <div>
        <%= f.label :password_confirmation, 'Confirm' %>:
        <%= f.password_field :password_confirmation, size: 40 %>
      </div>
      
      <div>
        <%= f.submit %>
      </div>
    </fieldset>
  
  <% end %>
</div>

AlxOnRails/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

AlxOnRails/app/views/users/index.html.erb
<h1>Listing users</h1>
  <% if notice %>
    <p id="notice"><%= notice %></p>
  <% end %>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

AlxOnRails/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

AlxOnRails/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>